# Generated by Django 5.2.1 on 2026-06-23 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferenceChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(blank=True, default=list, help_text='[{role: user|assistant, content: str}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_spend_cap', models.PositiveIntegerField(blank=True, help_text='Target monthly OTT spend cap in KRW', null=True)),
                ('preferred_genre_ids', models.JSONField(blank=True, default=list, help_text='TMDB genre IDs explicitly chosen by user')),
                ('consumption_habits', models.JSONField(blank=True, default=dict, help_text='e.g. binge, family, late_night, documentary_heavy')),
                ('platform_criteria', models.JSONField(blank=True, default=list, help_text='e.g. price, exclusives, quality, kids')),
                ('genre_weights', models.JSONField(blank=True, default=dict, help_text='LLM-parsed genre_id -> weight (0.0-1.0)')),
                ('taste_summary', models.TextField(blank=True)),
                ('onboarding_chat_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTasteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(db_index=True)),
                ('genre_weights', models.JSONField(blank=True, default=dict)),
                ('llm_summary', models.TextField(blank=True)),
                ('reaction_like_count', models.PositiveIntegerField(default=0)),
                ('reaction_dislike_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analysis_date'],
                'unique_together': {('user', 'analysis_date')},
            },
        ),
    ]
