# Generated by Django 5.2.1 on 2026-06-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usertasteanalysis_multiple_per_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertasteanalysis',
            options={'ordering': ['-analysis_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='usertasteanalysis',
            index=models.Index(fields=['user', 'analysis_date'], name='accounts_us_user_id_539410_idx'),
        ),
    ]
