# Generated by Django 5.2.1 on 2026-06-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usertasteanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blur_sensitive_thumbnails',
            field=models.BooleanField(default=True, help_text='Blur thumbnails for sensitive/inappropriate titles when True'),
        ),
    ]
