# Generated by Django 5.2.1 on 2026-06-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_blur_sensitive_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blur_sensitive_thumbnails',
        ),
    ]
