# Generated by Django 5.2.1 on 2026-06-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_blur_sensitive_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferenceprofile',
            name='taste_title_genre',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userpreferenceprofile',
            name='taste_title_habit',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='usertasteanalysis',
            name='taste_title_genre',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='usertasteanalysis',
            name='taste_title_habit',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
