# Generated by Django 5.2.1 on 2026-06-05 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('watchmode_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('korean_title', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('backdrop_url', models.URLField(blank=True)),
                ('release_date', models.DateField(null=True)),
                ('rating', models.FloatField(default=0)),
                ('content_type', models.CharField(max_length=20)),
                ('sources_synced_at', models.DateTimeField(blank=True, help_text='Last Watchmode availability sync; used for 24h cache TTL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sub', 'Subscription'), ('rent', 'Rent'), ('buy', 'Buy'), ('free', 'Free')], default='sub', max_length=5)),
                ('price', models.PositiveIntegerField(blank=True, help_text='Rent/buy price (KRW)', null=True)),
                ('deeplink_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_sources', to='contents.content')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.platform')),
            ],
            options={
                'unique_together': {('content', 'platform', 'source_type')},
            },
        ),
    ]
