# Generated by Django 5.2.1 on 2026-06-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='App-store surcharge prices, affiliate discounts, download limits, etc.'),
        ),
    ]
