# Generated by Django 5.2.1 on 2026-06-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchmodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='sources_cache',
            field=models.JSONField(blank=True, default=list, help_text='Cached merged provider list (RapidAPI + Watchmode) for the frontend'),
        ),
        migrations.AlterField(
            model_name='content',
            name='sources_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last availability sync; used for 24h cache TTL', null=True),
        ),
    ]
