# Generated by Django 5.2.1 on 2026-06-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_watchmodeusage_content_sources_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='watchmode_checked',
            field=models.BooleanField(default=False, help_text='Whether a Watchmode lookup has been attempted for the current cache window'),
        ),
    ]
