# Generated by Django 5.2.1 on 2026-06-23 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_contentreaction'),
        ('subscriptions', '0005_customplatformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMJudgmentCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('judgment_type', models.CharField(choices=[('exclusivity_weight', 'Exclusivity weight'), ('price_beneficial', 'Price beneficial')], max_length=30)),
                ('target_id', models.CharField(help_text='tmdb_id or plan_id depending on judgment_type', max_length=64)),
                ('result_json', models.JSONField(default=dict)),
                ('snapshot_date', models.DateField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['judgment_type', 'snapshot_date'], name='contents_ll_judgmen_c17aca_idx')],
            },
        ),
        migrations.CreateModel(
            name='TitleGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], max_length=10)),
                ('genre_id', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['genre_id'], name='contents_ti_genre_i_768b4d_idx')],
                'unique_together': {('tmdb_id', 'media_type', 'genre_id')},
            },
        ),
        migrations.CreateModel(
            name='TitleMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], max_length=10)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('popularity', models.FloatField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['media_type', 'vote_average'], name='contents_ti_media_t_603cb1_idx')],
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='PlatformBenchmarkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('availability_score', models.FloatField(blank=True, null=True)),
                ('exclusivity_score', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('price_score', models.FloatField(blank=True, null=True)),
                ('accessibility_score', models.FloatField(blank=True, null=True)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('value_score', models.FloatField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_snapshots', to='subscriptions.platform')),
            ],
            options={
                'ordering': ['-snapshot_date', 'platform__name'],
                'unique_together': {('platform', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='PlatformGenreStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.PositiveIntegerField(db_index=True)),
                ('title_count', models.PositiveIntegerField(default=0)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_stats', to='subscriptions.platform')),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'snapshot_date'], name='contents_pl_platfor_be269c_idx')],
                'unique_together': {('platform', 'genre_id', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='StreamingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV')], max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_cache_entries', to='subscriptions.platform')),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'available'], name='contents_st_platfor_2cf610_idx'), models.Index(fields=['tmdb_id', 'media_type'], name='contents_st_tmdb_id_25c6de_idx')],
                'unique_together': {('tmdb_id', 'media_type', 'platform')},
            },
        ),
    ]
