# Generated by Django 5.2.1 on 2026-06-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_llmjudgmentcache_titlegenres_titlemeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmjudgmentcache',
            name='judgment_type',
            field=models.CharField(choices=[('exclusivity_weight', 'Exclusivity weight'), ('price_beneficial', 'Price beneficial'), ('user_taste', 'User taste analysis'), ('onboarding_parse', 'Onboarding preference parse')], max_length=30),
        ),
    ]
