# Generated by Django 5.2.1 on 2026-06-23 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_llmjudgmentcache_judgment_type'),
        ('subscriptions', '0005_customplatformsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemeta',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='titlemeta',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='llmjudgmentcache',
            name='judgment_type',
            field=models.CharField(choices=[('exclusivity_weight', 'Exclusivity weight'), ('price_beneficial', 'Price beneficial'), ('user_taste', 'User taste analysis'), ('onboarding_parse', 'Onboarding preference parse'), ('platform_insight', 'Platform benchmark insight')], max_length=30),
        ),
        migrations.CreateModel(
            name='PlatformUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='1-5 user rating')),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='subscriptions.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('platform', 'user')},
            },
        ),
    ]
