# Generated by Django 5.2.1 on 2026-06-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_platform_review_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemeta',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Adult or mature rating (19+/NC-17/TV-MA) — blur thumbnail when enabled'),
        ),
    ]
