# Generated by Django 5.2.1 on 2026-06-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_titlemeta_is_sensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlemeta',
            name='sensitivity_checked',
            field=models.BooleanField(default=False, help_text='True after TMDB adult/rating lookup has been performed'),
        ),
    ]
