# Generated by Django 5.2.1 on 2026-06-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_titlemeta_sensitivity_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlemeta',
            name='is_sensitive',
        ),
        migrations.RemoveField(
            model_name='titlemeta',
            name='sensitivity_checked',
        ),
    ]
