"""
Django settings for whatsub project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import re
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

# backend/ is the Django app root; 10-pjt/ is the monorepo root (frontend, .env).
BACKEND_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BACKEND_DIR.parent
BASE_DIR = BACKEND_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cpvit42mjod71%xgcv3nguvxn(6&h_hd1@nzee!j+kskh^zsr$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'allauth.socialaccount.providers.google',
    'accounts',
    'contents',
    'community',
    'detector',
    'notifications',
    'subscriptions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whatsub.middleware.DevRelaxedCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'whatsub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'whatsub.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (platform/provider icons live under subscriptions/media)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'subscriptions' / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

FRONTEND_URL = 'http://127.0.0.1:5173'
BACKEND_URL = 'http://127.0.0.1:8000'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/onboarding/'
LOGOUT_REDIRECT_URL = f'{FRONTEND_URL}/login'

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',

    'allauth.account.auth_backends.AuthenticationBackend',
)

SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'openid',
            'profile',
            'email',
            'https://www.googleapis.com/auth/gmail.readonly',
        ],

        'AUTH_PARAMS': {
            'access_type': 'offline',
            'prompt': 'consent',
            'include_granted_scopes': 'true',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# Send the user straight to Google on click (skip allauth's intermediate page),
# and don't gate local signups behind email verification in development.
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'

SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

import environ
import os

env = environ.Env(
    # 기본값 설정 (선택사항)
    DEBUG=(bool, False)
)

# .env 파일을 읽어옵니다
environ.Env.read_env(PROJECT_ROOT / '.env')

DEBUG = env('DEBUG')
SECRET_KEY = env('SECRET_KEY')
FRONTEND_URL = env('FRONTEND_URL', default=FRONTEND_URL)
BACKEND_URL = env('BACKEND_URL', default=BACKEND_URL)
LOGIN_REDIRECT_URL = '/accounts/onboarding/'
LOGOUT_REDIRECT_URL = f'{FRONTEND_URL}/login'

# Database — DATABASE_URL unset → local SQLite. Set for Supabase/Postgres.
# migrate: use Supabase Session/direct URI (port 5432). Runtime: pooler (6543) OK.


def _sanitize_supabase_database_url(url: str) -> str:
    """Remove Supabase-only query params (e.g. pgbouncer=true) that psycopg2 rejects."""
    url = url.strip().strip('"').strip("'")
    parsed = urlparse(url)
    kept = [
        (key, value)
        for key, value in parse_qsl(parsed.query, keep_blank_values=True)
        if key.lower() != 'pgbouncer'
    ]
    clean = urlunparse(parsed._replace(query=urlencode(kept)))
    clean = re.sub(r'([?&])pgbouncer(=[^&]*)?&?', r'\1', clean, flags=re.IGNORECASE)
    return clean.rstrip('?&')


def _strip_pgbouncer_option(db_config: dict) -> None:
    options = db_config.get('OPTIONS') or {}
    for key in list(options):
        if key.lower() == 'pgbouncer':
            del options[key]
    if options:
        db_config['OPTIONS'] = options
    elif 'OPTIONS' in db_config:
        del db_config['OPTIONS']


_database_url = env.str('DATABASE_URL', default='')
if _database_url:
    DATABASES = {
        'default': env.db_url_config(_sanitize_supabase_database_url(_database_url)),
    }
    _db = DATABASES['default']
    if _db['ENGINE'] == 'django.db.backends.postgresql':
        _strip_pgbouncer_option(_db)
        _db['CONN_MAX_AGE'] = 0  # required for Supabase pgbouncer transaction mode
        _db.setdefault('OPTIONS', {})
        _db['OPTIONS'].setdefault('sslmode', 'require')
        _db['OPTIONS'].setdefault('connect_timeout', 10)
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

_DEV_VITE_PORTS = tuple(range(5173, 5200))


def _dev_frontend_origins(frontend_url):
    origins = {frontend_url.rstrip('/')}
    for port in _DEV_VITE_PORTS:
        origins.add(f'http://127.0.0.1:{port}')
        origins.add(f'http://localhost:{port}')
    return sorted(origins)


CSRF_TRUSTED_ORIGINS = sorted({
    BACKEND_URL.rstrip('/'),
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    *_dev_frontend_origins(FRONTEND_URL),
})

CORS_ALLOWED_ORIGINS = _dev_frontend_origins(FRONTEND_URL)
CORS_ALLOW_CREDENTIALS = True

# 우리가 사용할 API 키들
TMDB_API_KEY = env('TMDB_API_KEY', default='')
WATCHMODE_API_KEY = env('WATCHMODE_API_KEY', default='')
# RapidAPI streaming-availability key. Accept both spellings (RAPID_API_KEY / RAPIDAPI_KEY).
RAPIDAPI_KEY = env('RAPID_API_KEY', default=env('RAPIDAPI_KEY', default=''))
AI_API_KEY = env('AI_API_KEY', default=env('GMS_KEY', default=''))
AI_API_BASE = env(
    'AI_API_BASE',
    default='https://gms.ssafy.io/gmsapi/api.openai.com/v1',
)
AI_MODEL = (env('AI_MODEL', default='gpt-4o-mini') or 'gpt-4o-mini').strip().strip("'\"")
if not AI_MODEL:
    AI_MODEL = 'gpt-4o-mini'
AI_SCORING_MODEL = (
    env('AI_SCORING_MODEL', default='gpt-5.2') or 'gpt-5.2'
).strip().strip("'\"")
if not AI_SCORING_MODEL:
    AI_SCORING_MODEL = 'gpt-5.2'
AI_INSIGHT_MODEL = (
    env('AI_INSIGHT_MODEL', default='gpt-5.2') or 'gpt-5.2'
).strip().strip("'\"")
if not AI_INSIGHT_MODEL:
    AI_INSIGHT_MODEL = 'gpt-5.2'
AI_VISION_MODEL = (
    env('AI_VISION_MODEL', default='gemini-2.5-flash') or 'gemini-2.5-flash'
).strip().strip("'\"")
if not AI_VISION_MODEL:
    AI_VISION_MODEL = 'gemini-2.5-flash'
AI_VISION_API_BASE = env(
    'AI_VISION_API_BASE',
    default='https://gms.ssafy.io/gmsapi/generativelanguage.googleapis.com/v1beta',
)
GMAIL_PIPELINE_LOG = env.bool('GMAIL_PIPELINE_LOG', default=True)

if GMAIL_PIPELINE_LOG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'gmail_pipeline': {
                'format': '[gmail] %(message)s',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'gmail_pipeline',
            },
        },
        'loggers': {
            'detector.gmail': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

# Google OAuth credentials (from Google Cloud Console). When present, configure
# the allauth Google provider directly from settings so no DB SocialApp is needed.
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET', default='')
if GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS['google']['APP'] = {
        'client_id': GOOGLE_CLIENT_ID,
        'secret': GOOGLE_CLIENT_SECRET,
        'key': '',
    }
