# Generated by Django 5.2.1 on 2026-06-05 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('country', models.CharField(choices=[('KR', 'Korea'), ('GLOBAL', 'Global')], default='KR', max_length=10)),
                ('tmdb_provider_id', models.PositiveIntegerField(blank=True, help_text='TMDB watch-provider id (Netflix=8, Disney+=337, ...)', null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='subscriptions.category')),
            ],
        ),
        migrations.CreateModel(
            name='AddOnPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_name', models.CharField(max_length=100)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_passes', to='subscriptions.platform')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0, help_text='KRW; 0 = free')),
                ('billing_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('max_streams', models.PositiveSmallIntegerField(default=1)),
                ('max_quality', models.CharField(choices=[('SD', 'SD'), ('HD', 'HD'), ('FHD', 'FHD'), ('4K', '4K')], default='HD', max_length=4)),
                ('has_download', models.BooleanField(default=False)),
                ('has_ads', models.BooleanField(default=False)),
                ('is_bundle', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='subscriptions.platform')),
                ('requires_membership', models.ForeignKey(blank=True, help_text='e.g. Coupang Play 와우 requires the Coupang WOW plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_plans', to='subscriptions.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='BundleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_bundles', to='subscriptions.platform')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_contents', to='subscriptions.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='AddOnPassPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='KRW')),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('addon_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='subscriptions.addonpass')),
                ('base_plan', models.ForeignKey(blank=True, help_text='Base tier this price applies to; null = non-member price', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_pricings', to='subscriptions.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('payment_amount', models.PositiveIntegerField()),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
