# Generated by Django 5.2.1 on 2026-06-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_customplatformsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPlatformSubmission',
        ),
    ]
