# Generated by Django 5.2.1 on 2026-06-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_communitycommentreport_communitypostreport'),
        ('subscriptions', '0005_customplatformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='subscriptions.platform'),
        ),
    ]
